import type { Metadata } from "next";
import { Nabla } from "next/font/google";
import "./globals.css";
import { MainNav } from "./components/MainNav";
import { Footer } from "./components/Footer";

const nabala = Nabla({
  variable: "--font-nabla",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${nabala.variable} antialiased`}>
        <div className=" relative">
          <MainNav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
